queue_rules:
  - name: default
    merge_method: squash
    branch_protection_injection_mode: queue
    queue_conditions: &default_conditions
      - "base = master"
      - "-draft"
      - "-conflict"
      - "#approved-reviews-by >= 1"
      - "#changes-requested-reviews-by = 0"
      - "github-review-approved"
      - "github-require-last-push-approval"
      - "github-code-owner-review-satisfied"
    merge_conditions: *default_conditions

merge_protections_settings:
  reporting_method: check-runs
  auto_merge_conditions:
    - "base = master"

merge_protections:
  - name: default
    if:
      - "base = master"
    success_conditions: *default_conditions
