exec-once=dbus-update-activation-environment --systemd --all WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=systemctl --user import-environment QT_QPA_PLATFORMTHEME WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=1password --silent
exec-once=solaar -w hide
monitor=,preferred,auto,auto
windowrulev2=suppressevent maximize, class:.*
env = NIXOS_OZONE_WL, 1
env = NIXPKGS_ALLOW_UNFREE, 1
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland
env = GDK_BACKEND, wayland, x11
env = CLUTTER_BACKEND, wayland
env = QT_QPA_PLATFORM=wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1
env = QT_AUTO_SCREEN_SCALE_FACTOR, 1
env = SDL_VIDEODRIVER, x11
env = MOZ_ENABLE_WAYLAND, 1

cursor {
  hide_on_key_press=true
  inactive_timeout=10
}

decoration {
  blur {
    enabled=true
    passes=2
    popups=true
    size=16
    special=true
  }

  shadow {
    color=rgba(24273a99)
  }
  active_opacity=0.980000
  dim_inactive=false
  inactive_opacity=0.800000
  rounding=10
}

dwindle {
  preserve_split=true
  pseudotile=true
}

general {
  border_size=1
  col.active_border=rgb(8aadf4)
  col.inactive_border=rgb(494d64)
  gaps_in=3
  gaps_out=0
  layout=dwindle
}

group {
  groupbar {
    col.active=rgb(8aadf4)
    col.inactive=rgb(494d64)
    text_color=rgb(cad3f5)
  }
  col.border_active=rgb(8aadf4)
  col.border_inactive=rgb(494d64)
  col.border_locked_active=rgb(8bd5ca)
}

input {
  follow_mouse=2
}

master {
  new_status=master
}

misc {
  background_color=rgb(24273a)
  disable_hyprland_logo=true
  disable_splash_rendering=true
  focus_on_activate=true
  font_family=JetBrainsMono Nerd Font
  key_press_enables_dpms=true
  mouse_move_enables_dpms=true
}
$mainMod = SUPER
$terminal=kitty
$menu = fuzzel
$logout = wlogout
$browser = firefox
$filemanager = $terminal
bind = $mainMod SHIFT,Q,exec,/nix/store/zn114jnx2hhgdd2j3ml4gr9bcxc4f88x-wlogout-1.2.2/bin/wlogout
bind = $mainMod, T,exec,$terminal
bind = $mainMod, B, exec,$browser
bind = $mainMod, C, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, F, togglefloating,
bind = $mainMod, RETURN, fullscreen
bind = $mainMod, G, togglegroup,
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod, P, pseudo,
bind = $mainMod SHIFT, T, togglesplit,
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
bind = $mainMod CONTROL, J, changegroupactive, f
bind = $mainMod CONTROL, K, changegroupactive, b
bind = $mainMod SHIFT, h, movewindoworgroup, l
bind = $mainMod SHIFT, j, movewindoworgroup, d
bind = $mainMod SHIFT, k, movewindoworgroup, u
bind = $mainMod SHIFT, l, movewindoworgroup, r
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod,R,submap,resize
submap=resize
binde=,l,resizeactive,10 0
binde=,h,resizeactive,-10 0
binde=,k,resizeactive,0 -10
binde=,j,resizeactive,0 10
bind=,ESCAPE,submap,reset
bind=,RETURN,submap,reset
bind=,catchall,submap,reset
submap=reset
