background {
  blur_passes=2
  brightness=0.500000
  contrast=1
  path=/nix/store/1ffgqj1wd57rrdq4zd94scsd21sfd6r6-wallpaper.png
  vibrancy=0.200000
  vibrancy_darkness=0.200000
}

general {
  disable_loading_bar=true
  grace=10
  hide_cursor=false
  no_fade_in=false
  no_fade_out=false
}

image {
  size=400
  border_color=#cdd6f4
  border_size=2
  halign=center
  path=/nix/store/rzsjd3wqfz14ywlvxhbqbfjb3vgc3mki-profile-picture.jpg
  position=0, -100
  valign=center
}

input-field {
  size=800, 60
  dots_center=true
  dots_size=0.200000
  dots_spacing=0.350000
  fade_on_empty=false
  halign=center
  hide_input=false
  outline_thickness=3
  placeholder_text=<i>YOU SHALL NOT PASS...unless you have the right password, man.</i>
  position=0, -200
  rounding=-1
  valign=center
}

label {
  color=rgba (242, 243, 244, 0.75)
  font_family=JetBrainsMono Nerd Font
  font_size=22
  halign=center
  position=0, 300
  text=cmd[update:1000] echo "$(date +"%A, %B %d")"

  valign=center
}

label {
  color=rgba(242, 243, 244, 0.75)
  font_family=JetBrainsMono Nerd Font
  font_size=22
  halign=center
  position=0, 300
  text=cmd[update:1000] echo "$(date +"%A, %B %d")"

  valign=center
}

label {
  color=rgba(242, 243, 244, 0.75)
  font_family=JetBrainsMono Nerd Font
  font_size=22
  halign=center
  position=0, 300
  text=cmd[update:1000] echo "$(date +"%A, %B %d")"

  valign=center
}

label {
  color=rgba(242, 243, 244, 0.75)
  font_family=JetBrainsMono Nerd Font Extrabold
  font_size=95
  halign=center
  position=0, 200
  text=cmd[update:1000] echo "$(date +"%-I:%M")"

  valign=center
}
