general {
  after_sleep_cmd=hyprctl dispatch dpms on
  ignore_dbus_inhibit=false
  lock_cmd=pidof hyprlock || hyprlock
}

listener {
  on-timeout=pidof hyprlock || hyprlock
  timeout=200
}

listener {
  on-resume=hyprctl dispatch dpms on
  on-timeout=hyprctl dispatch dpms off
  timeout=600
}
